### PR TITLE
Converted show IDs from strings to ints

### PR DESCRIPTION
**Pull request by maddievb**

### CODE REVIEW

**Review by ethansaxenian — APPROVED** [review]
Looks good 1/3

**Review by ethanberner — APPROVED** [review]
Great! 2/3

**Review by schester77 — APPROVED** [review]
Wait actually, should we also change the sampleShows in the test.js files to have ids that are ints?

**Review by Cliffy2000 — APPROVED** [review]

**Comment by ethansaxenian** [comment]
> Wait actually, should we also change the sampleShows in the test.js files to have ids that are ints?

Good catch, I agree.

**Comment by maddievb** [comment]
Ok will do!

**Review by ethansaxenian — APPROVED** [review]

**Review by schester77 — APPROVED** [review]
cool

**Review by ethanberner — APPROVED** [review]

**Pull request merged**
