### PR TITLE
Authentication 'front end'

### PR DESCRIPTION
**Pull request by ethansaxenian**
We added the ability for users to log in using Auth0. Only emails that end in `@middlebury.edu` are allowed to log in. Essentially the `loggedIn` state has be replaced with `session`, and the session provider in `__app.js` means that we don't need to pass the session as a prop, rather we can just call `useSession()` inside our components.

For testing, we can now mock the `useSession` call to simulate a user being logged in or out. To do this, we need to mock the entire nextAuth module using `jest.mock("next-auth/client")` at the top of the file. This however will break any tests that require the normal functionality of `useSession`. So we've created a new file `auth.test.js` to separate the test suites that require mocking the module from those that don't.

We haven't yet connected the user accounts to a database; when the database is implemented we can add in the nextAuth tables. For the folks working on the database, we will also need a `userID` foreign key for the `show` table.

### CODE REVIEW

**Comment by ethansaxenian** [comment]
Well, it turns out we want to mock `useSession` for every test that calls it anyways (this makes our tests a bit faster as they aren't checking for authentication each time), so I put all the tests from `auth.test.js` back into `index.test.js`. So now we need to mock `useSession` in the `beforeEach` or `beforeAll` of the test suites in `index.test.js`.

**Comment by schester77** [comment]
Hmm, I'm getting a message "unable to connect" when I try to sign in. Maybe this is a problem with my browser? I'll look into it later, but thought I'd just mention it now if anyone else has the same issue.

**Comment by ethansaxenian** [comment]
Oh yeah, your replit needs to be configured as an allowed callback URL in the Auth0 app. @ethanberner is the app owner, so he will need to do this for our repls (and the heroku app, now that I think of it). For now you can use my repl, it should be working on there.

**Comment by ethanberner** [comment]
I've updated the callback permissions on Auth0 and added everybody's development servers extended by `/api/auth/callback/auth0` as well as the heroku app. Let me know if it still throws an error.

**Review by maddievb — APPROVED** [review]
looks good to me! (1/3)

**Review by Cliffy2000 — APPROVED** [review]
Looks great! (2/3)

**Review by madurst22 — APPROVED** [review]
Well done! (3/3)

**Pull request merged**
