### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by maddievb**
Lots of changes in this PR! Added routes for /schedule and /about, created dynamic routes to display shows and playlists, and rewrote some tests to accommodate these changes. One aspect of the playlist logging functionality is missing (changes persist when you navigate away from the page) and I'm hoping we can talk about that in our meeting today!

This PR is also all functionality. A styling PR is coming soon!

### CODE REVIEW

**Comment by ethansaxenian** [comment]
Hmm, it looks like you can't navigate back to the home page once you've started logging a playlist (you have to go to the schedule/about and then home). I guess the solution would either be to make the `PlaylistLogger` its own page or pass the `setLoggingPlaylist` callback into `NavBar`.

**Review by ethansaxenian — APPROVED** [review]
Beautiful, wonderful, and amazing. A+ (1/3)

**Review by madurst22 — APPROVED** [review]
Only thing is the use of _ instead of our drinking camel case. Was a lot of work, great job!!! (2/3)

**Review by ethanberner — APPROVED** [review]
awesome job! 3/3

**Pull request merged**
