### PR TITLE
Log playlist

### LINKED ISSUE #8: As a DJ, I want to be able to log my playlists for my show, so listeners can keep track of what I'm playing.
- Log one song at a time or type them in all at once.
- After entering a song, would like to see if the API fetched the album cover correctly, so we can update it if necessary
- Type in Title, Artist, and Album
- Can delete or update a song

### PR DESCRIPTION
**Pull request by maddievb**
When a user gets to the homepage, they can log in, select one of their shows from the dropdown menu, and then start logging a playlist. They can add new rows, enter title/artist/album for each song, update these fields, and delete songs. Once they're done, they can end the show (or it will end automatically when they log out).

### CODE REVIEW

**Review by schester77 — APPROVED** [review]
nice! 1/3

**Review by ethanberner — APPROVED** [review]
awesome job! 2/3

**Review by madurst22 — APPROVED** [review]
Looks good! Only question: why use randomly generated IDs rather than a sequential ID generation which would group songs from one playlist together? 3/3

**Comment by ethansaxenian** [comment]
> Looks good! Only question: why use randomly generated IDs rather than a sequential ID generation which would group songs from one playlist together? 3/3

Because we're (going to be) storing the songs in a database, we need to make sure they all have unique ids. The songs common to a single playlist should have `song.playlistID === playlist.id`.

**Pull request merged**
